#include "./include/sequence.h"


Sequence::Sequence()
{
    ROWS =0;
    COLS =0;
    sequenceName ="";
}
Sequence::Sequence(int rows, int cols, std::string name){
    ROWS =rows;
    COLS =cols;
    for (int i = 0; i < rows; i++) {
        std::vector<int> row;
        for (int j = 0; j < cols; j++) {
            row.push_back(0);
        }
        grid.push_back(row);
    }
    sequenceName = name;
}
void Sequence::save(){

}

// # Specification
//+The JSON file generated by import-layout is of the following format:
//+
//+```json
//+{
//+  "layoutName": "string:",
//+  "channels": [
//+    {
//+      "channelName": "string",
//+      "color": "string",
//+      "internalChannel": number (int),
//+      "dmxChannel": number (int),
//+      "fixtureName": "string",
//+      "location": "string",
//+      "rotation": "string"
//+    },
//+    ...
//+  ]
//+}
//+```
//+
//+color has format "XXXXXX", a 6-digit fixed-length hex code.
//+location is string of form "x,y,z". Currently not used.
//+rotation is string of form "a,b,c". Currently not used.
//+
//+
//+The JSON file generated by import-sequence is simply an array of arrays, channel-major order, with each value between 0-255.
